#!/bin/bash
source /etc/pulxc/pulxc.conf
CONFIG_PATH="$BASE_PATH/lxc/$1/config"
if [[ $1 == "" ]]; then
    echo "No Username"
    exit 1
fi
id $1 > /dev/null 2>&1
if [[ $? -ne 0 ]]; then
    echo "User didn't exist!"
    exit 1
fi
lxc-create -P $BASE_PATH/lxc -t $LXC_TEMPLATE -n "$1"
if [[ $? -ne 0 ]]; then
    exit 1
fi
echo "Finish Creating lxc"
notuid0=$(find $BASE_PATH/lxc/"$1"/rootfs -not -uid 0)
notgid0=$(find $BASE_PATH/lxc/"$1"/rootfs -not -gid 0)
facl=$(getfacl -R -s -p $BASE_PATH/lxc/"$1"/rootfs | grep "# file:" | awk '{print$3}')
if [[ "$notuid0" != "" ]]; then
    echo "Files not own by root"
    notuid0=$(echo "$notuid0" | awk '{printf "\"%s\" ",$1; system("stat -c \"%u\" "$1);}')
    echo "$notuid0"
fi
if [[ "$notgid0" != "" ]]; then
    echo "Files not grouped by root"
    notgid0=$(echo "$notgid0" | awk '{printf "\"%s\" ",$1; system("stat -c \"%g\" "$1);}')
    echo "$notgid0"
fi
chown -R $BASE_SUBUID:$BASE_SUBGID $BASE_PATH/lxc/"$1"/rootfs
if [[ "$notuid0" != "" ]]; then
    echo "$notuid0" | awk -v BASEUID=$BASE_SUBUID '{system("chown "$2+BASEUID" "$1);}'
fi
if [[ "$notgid0" != "" ]]; then
    echo "$notgid0" | awk -v BASEGID=$BASE_SUBGID '{system("chgrp "$2+BASEGID" "$1);}'
fi
if [[ "$facl" != "" ]]; then
    echo "Files using facl"
    echo "$facl" | while read filename;
    do
        echo "$filename"
        echo "==BEFORE=="
        getfacl -n $filename
        tmp=$(getfacl -p -n $filename)
        tmp=$(echo "$tmp" | grep '^[^#]' |
            awk -F: -vBASEUID=$BASE_SUBUID -vBASEGID=$BASE_SUBGID '{
                OFS=":";
                if($1!="default"&&$1=="user"&&$2!="")
                    {$2=$2+BASEUID}
                else if($1!="default"&&$1=="group"&&$2!="")
                    {$2=$2+BASEGID}
                else if($1=="default"&&$2=="user"&&$3!="")
                    {$3=$3+BASEUID}
                else if($1=="default"&&$2=="group"&&$3!="")
                    {$3=$3+BASEGID}
                print$0;
            }')
        setfacl -b $filename
        echo "$tmp" | setfacl -M - $filename
        echo "==AFTER=="
        getfacl -n $filename
    done
fi

chown $BASE_SUBUID:$USER $BASE_PATH/lxc/$1
chown $USER:$USER $CONFIG_PATH
sed -i 's/lxc.net.0.type = empty//g' $CONFIG_PATH
echo "lxc.include = /usr/share/lxc/config/userns.conf" >> $CONFIG_PATH
echo "lxc.include = /etc/pulxc/pulxc-lxc.conf" >> $CONFIG_PATH
echo "lxc.idmap = u 0 $BASE_SUBUID 65536" >> $CONFIG_PATH
echo "lxc.idmap = g 0 $BASE_SUBGID 65536" >> $CONFIG_PATH
nextip=$(cat $BASE_PATH/nextip)
echo "lxc.net.0.type = veth" >> $CONFIG_PATH
echo "lxc.net.0.link = $BRIDGE_INTERFACE" >> $CONFIG_PATH
echo "lxc.net.0.ipv4.address = $IP_PREFIX.$nextip/24" >> $CONFIG_PATH
echo "lxc.net.0.ipv4.gateway = $GATEWAY" >> $CONFIG_PATH
echo "lxc.net.0.name = eth0" >> $CONFIG_PATH
echo "lxc.net.0.flags = up" >> $CONFIG_PATH
echo "Using ip $IP_PREFIX.$nextip/24"
nextip=$(($nextip+1))
echo $nextip > $BASE_PATH/nextip
